# Generated by Django 2.1.15 on 2023-09-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
    ]
