# Generated by Django 2.1.15 on 2023-09-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_newpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='image',
        ),
    ]
