# Generated by Django 2.1.15 on 2023-09-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_newpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='categories',
        ),
    ]
