# Generated by Django 2.1.15 on 2023-09-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_newpost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
