# Generated by Django 2.1.15 on 2023-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20230925_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
