# Generated by Django 4.2.5 on 2023-10-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_profile_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_page',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
