# Generated by Django 4.2.5 on 2023-10-04 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0009_profile_page_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_page',
            new_name='profilepage',
        ),
    ]
