# Generated by Django 4.2.5 on 2023-10-04 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0010_rename_profile_page_profilepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='username',
        ),
        migrations.AddField(
            model_name='profilepage',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
